# backend/pathfinder/survey/report_labels.py — 설문 리포트 마크다운의 라벨.
#
# 이것은 UI 문구가 아니라 **문서 생성기**다. 리포트는 aiplc-docs/** 아래에
# 산출물로 저장되고 문서 리뷰 화면과 개발자 핸드오프에 들어가므로, UI 언어
# (사용자별 쿠키)가 아니라 프로젝트 언어를 따른다.
#
# error_codes.py의 "백엔드에 번역 시스템을 만들지 않는다"와 모순되지 않는다:
# 그쪽은 사용자에게 보이는 에러 문구이고 UI 언어를 백엔드가 모른다. 여기는
# 문서이고 프로젝트 언어를 백엔드가 이미 안다.
#
# 영어를 그대로 두는 헤딩이 있다: prototype-validation.md Step 6이 정한 섹션
# 이름(`## Feedback Sources`, `## Theme Analysis`, `## Pain Point Mapping`,
# `## Build Decision`)과 그 표 헤더는 **양쪽 언어에서 영어다.** 룰이 그 이름으로
# 문서를 찾고, 상류 워크플로우가 그 구조를 전제하기 때문이다.
from __future__ import annotations

_LANGUAGES = ("ko", "en")
_DEFAULT = "ko"

_LABELS = {
    "ko": {
        "prototype": "프로토타입",
        "survey": "설문",
        "hypothesis": "검증 가설",
        "response_count": "응답 수",
        "survey_status": "설문 상태",
        "collected_at": "취합 시각",
        "status_closed": "마감",
        "status_open": "진행 중",
        "source_name": "Pathfinder 검증 설문",
        "note": ("> 이 파일은 Pathfinder 설문 집계로 생성되었다. 아래 '정량 집계'와\n"
                 "> '자유 응답 전문'은 수집된 데이터이며, 테마 분석·pain point 매핑·\n"
                 "> 빌드 결정은 PM이 판단해 채운다(prototype-validation.md Step 6)."),
        "quantitative": "정량 집계",
        "free_text": "자유 응답 전문",
        "mean": "평균",
        "of_5": "/ 5",
        "responses_n": "응답 {n}건",
        "score": "점수",
        "count": "응답 수",
        "option": "선택지",
        "ratio": "비율",
        "free_n": "자유 응답 {n}건 — 전문은 아래 '자유 응답 전문' 참조",
        "no_response": "(응답 없음)",
        "theme_placeholder": "(PM이 위 자유 응답에서 도출)",
        "pain_placeholder": "(Envision의 pain point를 옮겨 판정)",
        "decision_proceed": "Proceed — 검증됨, 다음 단계로",
        "decision_iterate": "Iterate — 부분 검증, 프로토타입 수정 후 재검증",
        "decision_pivot": "Pivot — 접근 재고 (Envision으로 복귀)",
        "optional_suffix": " (선택)",
        "scale_hint": "1(전혀 아니다) ~ 5(매우 그렇다) 중 선택",
        "free_response": "(자유 응답)",
    },
    "en": {
        "prototype": "Prototype",
        "survey": "Survey",
        "hypothesis": "Validation hypothesis",
        "response_count": "Responses",
        "survey_status": "Survey status",
        "collected_at": "Aggregated at",
        "status_closed": "closed",
        "status_open": "open",
        "source_name": "Pathfinder validation survey",
        "note": ("> This file was generated by Pathfinder's survey aggregation. The\n"
                 "> quantitative summary and full free responses below are collected\n"
                 "> data; theme analysis, pain point mapping, and the build decision\n"
                 "> are for the PM to judge and fill in (prototype-validation.md\n"
                 "> Step 6)."),
        "quantitative": "Quantitative summary",
        "free_text": "Full free responses",
        "mean": "Mean",
        "of_5": "/ 5",
        "responses_n": "{n} responses",
        "score": "Score",
        "count": "Responses",
        "option": "Option",
        "ratio": "Share",
        "free_n": "{n} free responses — see 'Full free responses' below",
        "no_response": "(no responses)",
        "theme_placeholder": "(PM derives from the free responses above)",
        "pain_placeholder": "(carry over Envision's pain points and judge them)",
        "decision_proceed": "Proceed — validated, move on",
        "decision_iterate": "Iterate — partly validated, revise the prototype and retest",
        "decision_pivot": "Pivot — reconsider the approach (back to Envision)",
        "optional_suffix": " (optional)",
        "scale_hint": "Pick from 1 (not at all) to 5 (very much)",
        "free_response": "(free response)",
    },
}


def labels(language: str) -> dict[str, str]:
    """리포트 라벨 사전. 알 수 없는 언어는 한국어로 떨어진다."""
    return _LABELS[language if language in _LANGUAGES else _DEFAULT]
