# backend/aipds/survey/report_labels.py -- the labels in the survey report markdown.
#
# This is not UI wording but a **document generator**. The report is stored as an artifact
# under aiplc-docs/** and goes into the document review screen and the developer handoff, so it
# follows the project language rather than the UI language (a per-user cookie).
#
# It does not contradict error_codes.py's "we do not build a translation system in the
# backend": that one is error wording shown to a user, and the backend does not know the UI
# language. This is a document, and the backend already knows the project language.
#
# Some headings stay English: the section names Step 6 of prototype-validation.md fixes
# (`## Feedback Sources`, `## Theme Analysis`, `## Pain Point Mapping`, `## Build Decision`)
# and their table headers are **English in both languages.** The rules find the document by
# those names, and the upstream workflow presumes that structure.

# NOTE: the Korean strings below are the product itself -- the ko branch of a per-language
# pair, rendered into a Korean project's report. They must not be translated
# (tests/test_korean_product_strings.py holds a minimum count for this file).
from __future__ import annotations

_LANGUAGES = ("ko", "en")
_DEFAULT = "ko"

_LABELS = {
    "ko": {
        "prototype": "프로토타입",
        "survey": "설문",
        "hypothesis": "검증 가설",
        "response_count": "응답 수",
        "survey_status": "설문 상태",
        "collected_at": "취합 시각",
        "status_closed": "마감",
        "status_open": "진행 중",
        "source_name": "AI-PDS 검증 설문",
        "note": ("> 이 파일은 AI-PDS 설문 집계로 생성되었다. 아래 '정량 집계'와\n"
                 "> '자유 응답 전문'은 수집된 데이터이며, 테마 분석·pain point 매핑·\n"
                 "> 빌드 결정은 PM이 판단해 채운다(prototype-validation.md Step 6)."),
        "quantitative": "정량 집계",
        "free_text": "자유 응답 전문",
        "mean": "평균",
        "of_5": "/ 5",
        "responses_n": "응답 {n}건",
        "score": "점수",
        "count": "응답 수",
        "option": "선택지",
        "ratio": "비율",
        "free_n": "자유 응답 {n}건 — 전문은 아래 '자유 응답 전문' 참조",
        "no_response": "(응답 없음)",
        "theme_placeholder": "(PM이 위 자유 응답에서 도출)",
        "pain_placeholder": "(Envision의 pain point를 옮겨 판정)",
        "decision_proceed": "Proceed — 검증됨, 다음 단계로",
        "decision_iterate": "Iterate — 부분 검증, 프로토타입 수정 후 재검증",
        "decision_pivot": "Pivot — 접근 재고 (Envision으로 복귀)",
        "optional_suffix": " (선택)",
        "scale_hint": "1(전혀 아니다) ~ 5(매우 그렇다) 중 선택",
        "free_response": "(자유 응답)",
    },
    "en": {
        "prototype": "Prototype",
        "survey": "Survey",
        "hypothesis": "Validation hypothesis",
        "response_count": "Responses",
        "survey_status": "Survey status",
        "collected_at": "Aggregated at",
        "status_closed": "closed",
        "status_open": "open",
        "source_name": "AI-PDS validation survey",
        "note": ("> This file was generated by AI-PDS's survey aggregation. The\n"
                 "> quantitative summary and full free responses below are collected\n"
                 "> data; theme analysis, pain point mapping, and the build decision\n"
                 "> are for the PM to judge and fill in (prototype-validation.md\n"
                 "> Step 6)."),
        "quantitative": "Quantitative summary",
        "free_text": "Full free responses",
        "mean": "Mean",
        "of_5": "/ 5",
        "responses_n": "{n} responses",
        "score": "Score",
        "count": "Responses",
        "option": "Option",
        "ratio": "Share",
        "free_n": "{n} free responses — see 'Full free responses' below",
        "no_response": "(no responses)",
        "theme_placeholder": "(PM derives from the free responses above)",
        "pain_placeholder": "(carry over Envision's pain points and judge them)",
        "decision_proceed": "Proceed — validated, move on",
        "decision_iterate": "Iterate — partly validated, revise the prototype and retest",
        "decision_pivot": "Pivot — reconsider the approach (back to Envision)",
        "optional_suffix": " (optional)",
        "scale_hint": "Pick from 1 (not at all) to 5 (very much)",
        "free_response": "(free response)",
    },
}


def labels(language: str) -> dict[str, str]:
    """The report label dictionary. An unknown language falls back to Korean."""
    return _LABELS[language if language in _LANGUAGES else _DEFAULT]
